import { database } from '@/lib/db';
import { validateRecord } from '@/lib/model';
export async function GET(){try{const r=await database().prepare('SELECT * FROM records ORDER BY updated_at DESC').all();return Response.json(r.results.map((r:any)=>({...r,data:JSON.parse(r.data)})),{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'暂时无法加载记录，请稍后重试'},{status:500})}}
export async function POST(req:Request){return mutate(req,false)}
export async function PUT(req:Request){return mutate(req,true)}
async function mutate(req:Request,edit:boolean){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'请求来源无效'},{status:403});const body=await req.text();if(body.length>200000)throw new Error('记录内容过长');const b=JSON.parse(body);const data=validateRecord(b.kind,b.data);const db=database();const now=new Date().toISOString();let id=crypto.randomUUID();let revision=1;
if(edit){if(typeof b.id!=='string'||!Number.isInteger(b.revision))throw new Error('记录标识无效');id=b.id;revision=b.revision+1;const r=await db.prepare('UPDATE records SET data=?, revision=revision+1, updated_at=? WHERE id=? AND revision=? AND kind=?').bind(JSON.stringify(data),now,id,b.revision,b.kind).run();if(!r.meta.changes)return Response.json({error:'记录已在其他页面更新，请关闭编辑并刷新后再试'},{status:409});}
else await db.prepare('INSERT INTO records (id,kind,data,revision,updated_at) VALUES (?,?,?,?,?)').bind(id,b.kind,JSON.stringify(data),revision,now).run();return Response.json({id,kind:b.kind,data,revision,updated_at:now},{status:edit?200:201});}catch(e){return Response.json({error:e instanceof Error?e.message:'保存失败，请重试'},{status:400})}}
export async function DELETE(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'请求来源无效'},{status:403});const b=await req.json() as any;if(typeof b.id!=='string'||!Number.isInteger(b.revision))throw new Error('记录无效');const r=await database().prepare('DELETE FROM records WHERE id=? AND revision=?').bind(b.id,b.revision).run();if(!r.meta.changes)return Response.json({error:'记录已变更，请刷新后重试'},{status:409});return Response.json({ok:true})}catch{return Response.json({error:'删除失败，请重试'},{status:400})}}
